project:
  type: website
  render:
    - index.qmd
  resources:
    - figs/
    - resources/s2-html-example.html
    - resources/s2-html-example.css

metadata-files:
  - ../_shared.yml

format:
  revealjs:
    include-in-header:
      - resources/_header.html
      - ../styles/practice-timer.html
