project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: white
    slide-number: true
    chalkboard: true
    incremental: false
    transition: fade
    history: false
    embed-resources: false
